from decimal import Decimal

POLICY_VERSION = "1.0"

# These boundaries match ml/src/config.py and are intentionally not policy overrides.
LOW_RISK_UPPER = Decimal("0.30")
MEDIUM_RISK_UPPER = Decimal("0.70")

MAX_FAILED_PAYMENT_ATTEMPTS_24H = 5

RULE_INVALID_AMOUNT = "INVALID_PAYMENT_AMOUNT"
RULE_SENDER_INACTIVE = "SENDER_USER_INACTIVE"
RULE_SENDER_ACCOUNT_INACTIVE = "SENDER_ACCOUNT_INACTIVE"
RULE_RECEIVER_INACTIVE = "RECEIVER_USER_INACTIVE"
RULE_RECEIVER_ACCOUNT_INACTIVE = "RECEIVER_ACCOUNT_INACTIVE"
RULE_BENEFICIARY_INACTIVE = "BENEFICIARY_INACTIVE"
RULE_SELF_PAYMENT = "SELF_PAYMENT"
RULE_INSUFFICIENT_BALANCE = "INSUFFICIENT_SIMULATED_BALANCE"
RULE_EXCESSIVE_FAILED_ATTEMPTS = "EXCESSIVE_FAILED_PAYMENT_ATTEMPTS"
RULE_PAYMENT_NOT_PENDING = "PAYMENT_NOT_PENDING_RISK"
RULE_RISK_LEVEL_MISMATCH = "RISK_ASSESSMENT_LEVEL_MISMATCH"
RULE_PRIOR_FRAUD_HOLD = "PRIOR_FRAUD_HISTORY_HOLD"
RULE_REPEATED_FAILURES_HOLD = "REPEATED_FAILED_ATTEMPTS_HOLD"
RULE_LOW_RISK_APPROVAL = "LOW_RISK_AUTOMATIC_APPROVAL"
RULE_MEDIUM_RISK_VERIFY = "MEDIUM_RISK_REQUIRES_VERIFICATION"
RULE_HIGH_RISK_HOLD = "HIGH_RISK_TEMPORARY_HOLD"
